refactor : OIDC 인증 리팩토링
daedongbread/bread-map-backend-2 pull request #250
Opened 2023-06-01 14:09 UTC by JayPark7821

OICD 로직 리팩토링
dead code 제거

2023-06-01 15:28 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCVerifierTemplate.java
> +public abstract class OIDCVerifierTemplate {
템플릿 메서드 패턴으로

OIDCVerifierTemplate 상속받아
getOIDCPublicKeysDto 메서드 구현 시

추후 다른 소셜 로그인 지원 요구사항 발생 시 대응 가능

2023-06-04 16:55 UTC, grand7070 requested changes
와 덕분에 난잡했던 코드가 깔끔해졌습니다 감사합니다!!
기존 OAuth 로그인 로직 중 하나인 OAuth2AuthenticationSuccessHandler도 삭제해주시면 감사하겠습니다!
또 GoogleOIDCVerifier가 빠져있는 것 같습니다!

추가로 코드 보다가 궁금한게 있는데 어떤 지역 변수나 매개 변수에는 final이 들어가던데 혹시 final이 들어가는 것들의 기준이 궁금합니다!

2023-06-04 16:55 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCVerifyProcessorImpl.java
> +	public OIDCVerifyProcessorImpl(final List<OIDCVerifierTemplate> oidcVerifierList) {
이 부분은 @RequiredArgsConstructor로 대체 가능하지 않나요?

2023-06-04 16:55 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/verifier/AppleOIDCVerifier.java
> +	@Cacheable(cacheNames = "AppleOICD", cacheManager = "oidcCacheManager")
제가 구글, 애플, 카카오 cacheNames를 OIDC가 아닌 OICD로 잘못 적었는데 수정 해주실 수 있으실까요?ㅠ

2023-06-04 16:55 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/security/userinfo/OICDUserInfo.java
> +public class OICDUserInfo {
OICD 오타가 있습니다!

2023-06-04 16:55 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/infra/SecurityConfig.java
>   * Created by ParkSuHo by 2022/03/18.
혹시 해당 부분 삭제 해주실 수 있으실까요? ValidationSequence에도 있어서 부탁드리겠습니다!

2023-06-04 16:55 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/verifier/AppleOIDCVerifier.java
> +	private final AppleOAuthClient appleOAuthClient;
final 필드에 대해 생성자 주입을 위해 @RequiredArgsConstructor가 필요할 것 같습니다!

2023-06-04 22:52 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/verifier/AppleOIDCVerifier.java
> +	@Cacheable(cacheNames = "AppleOICD", cacheManager = "oidcCacheManager")
수정 완료요!!

2023-06-04 22:53 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/userinfo/OICDUserInfo.java
> +public class OICDUserInfo {
수정 완료요!!

2023-06-04 22:54 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/infra/SecurityConfig.java
>   * Created by ParkSuHo by 2022/03/18.
수정 완료요!!

2023-06-04 22:58 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCVerifyProcessorImpl.java
> +	public OIDCVerifyProcessorImpl(final List<OIDCVerifierTemplate> oidcVerifierList) {
직접 생성자 선언 대신 @RequiredArgsConstructor 사용하는 것으로 맞출게요!!
업무 볼 때 컨벤션이 어노테이션말고 직접 생성자 선언하기로 정해져가지고 습관처럼 사용하고 있었네요

2023-06-04 22:59 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/verifier/AppleOIDCVerifier.java
> +	private final AppleOAuthClient appleOAuthClient;
이것도 생성자로 주입받고있었는데 ㅎㅎ 
어노테이션으로 맞추겠습니다.

2023-06-05 02:56 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCVerifyProcessorImpl.java
> +	public OIDCVerifyProcessorImpl(final List<OIDCVerifierTemplate> oidcVerifierList) {
감사합니다!ㅎㅎ 컨벤션 관련해서는 알려주신 네이버 컨벤션 확인해서 빨리 논의 진행될 수 있게 하겠습니다!

2023-06-05 03:00 UTC, grand7070 requested changes

2023-06-05 03:00 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/auth/AuthServiceImpl.java
> +	private void createUser(OIDCUserInfo OIDCUserInfo, Boolean isMarketingInfoReceptionAgreed) {
ditto

2023-06-05 03:02 UTC, JayPark7821 commented
> 와 덕분에 난잡했던 코드가 깔끔해졌습니다 감사합니다!!
> 
> 기존 OAuth 로그인 로직 중 하나인 OAuth2AuthenticationSuccessHandler도 삭제해주시면 감사하겠습니다!
> 
> 또 GoogleOIDCVerifier가 빠져있는 것 같습니다!
> 
> 
> 
> 추가로 코드 보다가 궁금한게 있는데 어떤 지역 변수나 매개 변수에는 final이 들어가던데 혹시 final이 들어가는 것들의 기준이 궁금합니다!

인텔리 제이 설정에 기본적으로 final로 생성하도록 세팅하고 사용 중이고

final이 기본이고 필요에 따라 변경이 필요하다면 해당 키워드 제거 후 사용 중입니다

2023-06-05 04:06 UTC, JayPark7821 commented
아이고 이런 오타들을.... 🫣

2023-06-05 05:25 UTC, grand7070 commented
> > 와 덕분에 난잡했던 코드가 깔끔해졌습니다 감사합니다!!
> > 기존 OAuth 로그인 로직 중 하나인 OAuth2AuthenticationSuccessHandler도 삭제해주시면 감사하겠습니다!
> > 또 GoogleOIDCVerifier가 빠져있는 것 같습니다!
> > 추가로 코드 보다가 궁금한게 있는데 어떤 지역 변수나 매개 변수에는 final이 들어가던데 혹시 final이 들어가는 것들의 기준이 궁금합니다!
> 
> 인텔리 제이 설정에 기본적으로 final로 생성하도록 세팅하고 사용 중이고
> 
> final이 기본이고 필요에 따라 변경이 필요하다면 해당 키워드 제거 후 사용 중입니다

아하 이것도 컨벤션이었군요! 인텔리설정으로 매개 변수만 기본으로 생성이 되나요? 지역 변수는 직접 하신 걸까요?

2023-06-05 05:26 UTC, grand7070 approved these changes

2023-06-05 05:26 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCVerifierTemplate.java
> +			return new OIDCUserInfo(
OIDCUserInfo가 @Builder를 사용 중이니 여기서 빌더 패턴으로 하면 좋을 것 같습니다!

2023-06-05 06:16 UTC, JayPark7821 commented
> > > 와 덕분에 난잡했던 코드가 깔끔해졌습니다 감사합니다!!
> > > 기존 OAuth 로그인 로직 중 하나인 OAuth2AuthenticationSuccessHandler도 삭제해주시면 감사하겠습니다!
> > > 또 GoogleOIDCVerifier가 빠져있는 것 같습니다!
> > > 추가로 코드 보다가 궁금한게 있는데 어떤 지역 변수나 매개 변수에는 final이 들어가던데 혹시 final이 들어가는 것들의 기준이 궁금합니다!
> > 
> > 
> > 인텔리 제이 설정에 기본적으로 final로 생성하도록 세팅하고 사용 중이고
> > final이 기본이고 필요에 따라 변경이 필요하다면 해당 키워드 제거 후 사용 중입니다
> 
> 아하 이것도 컨벤션이었군요! 인텔리설정으로 매개 변수만 기본으로 생성이 되나요? 지역 변수는 직접 하신 걸까요?

인텔리제이 설정에서 해당 값 체크하시면 

![image](https://github.com/daedongbread/bread-map-backend-2/assets/60100532/2705bd28-ea03-4da6-80b8-6006e820b394)

extract variable, method 할떄 또는 메소드 구현할떄 자동으로 final을 붙여줘요!!!

2023-06-05 06:18 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCVerifierTemplate.java
> +			return new OIDCUserInfo(
넵 수정했습니다!!!

2023-06-05 06:20 UTC, merged