refactor : NoticeService::getNoticeList
daedongbread/bread-map-backend-2 pull request #251
Opened 2023-06-02 07:37 UTC by JayPark7821

NoticeDto 생성 로직을 NoticeGenerateFactory에 위임

일단은 NoticeType 추가 후 BiFunction만 구현하면
NoticeGenerateFactory를 사용하는 클라이언트 코드의 변경 없이 확장이 가능하도록 수정했는데

NoticeType enum이 조금 지저분해진 것 같아서
혹시 다른 좋은 방법이 떠오르시면 말씀 부탁드려요!!!!

2023-06-03 16:46 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/follow/UserFollowServiceImpl.java
> +		);
기존 : 각 이벤트별로 각기 다른 이벤트 생성 -> 각각 다른 이벤트 리스너에서 메시지 처리
변경 : 각 알림 이벤트 publisher에서 공통된 NoticableEvent만 생성 -> 한 개의 이벤트 리스너로 대응

2023-06-04 17:52 UTC, grand7070 requested changes
안그래도 이벤트별로 다른 NoticeEvent를 만들고 분기도 여러개 타서 많이 더러웠는데 깔끔해졌네요 감사합니다!ㅎㅎ

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
> +	private Long userId;
혹시 Entity로 연결 대신 이렇게 하신 이유가 있으신가요?

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/DefaultNoticeGenerateFactory.java
> +	public DefaultNoticeGenerateFactory(final CustomAWSS3Properties customAwss3Properties) {
여기 부분은 @RequiredArgsConstructor로 대체해도 될 것 같습니다!

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/DefaultNoticeGenerateFactory.java
> +		final Notice notice,
여기 depth?를 두신건 컨벤션인가요? 다른 곳에는 argument가 복수개여도 한 line인 것 같은데 여기 부분은 다른 이유가 궁금합니다!

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticableEvent.java
> +public class NoticableEvent {
혹시 해당 이름이 무슨 뜻인지 알 수 있을까요?

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
> +		public NoticeBaseInfo(final String image, final String title) {
여긴 @AllArgsConstructor로 대체 가능할 것 같습니다!

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
> +	public static class NoticeBaseInfo {
NoticeBaseInfo가 NoticeDto의 내부 필드 중 하나로 사용되지 않는 것 같은데 NoticeDto에서 분리하는 건 어떤가요?

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
> +		FirebaseMessagingException {
여기 부분도 컨벤션인가요?? 일단 단일 Exception은 throws 옆에 있는게 가독성이 좋은 것 같은데 어떻게 생각하시나요?

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
>   */
혹시 해당 주석 삭제해주실 수 있으실까요?ㅠㅜ

2023-06-04 17:52 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceImpl.java
> +					.noticeType(NoticeType.REVIEW_COMMENT)
이 부분은 RECOMMENT가 와야 할 것 같습니다!

2023-06-04 18:08 UTC, grand7070 commented
> NoticeDto 생성 로직을 NoticeGenerateFactory에 위임
> 
> 일단은 NoticeType 추가 후 BiFunction만 구현하면 NoticeGenerateFactory를 사용하는 클라이언트 코드의 변경 없이 확장이 가능하도록 수정했는데
> 
> NoticeType enum이 조금 지저분해진 것 같아서 혹시 다른 좋은 방법이 떠오르시면 말씀 부탁드려요!!!!

음 제가 잘 몰라서 그럴 수 있는데 Enum에서 Enum외의 것들(Notice, CustomAWSS3Properties)에 대해 저런식으로 들고가도 되는지 잘 모르겠습니다ㅠ 또 NoticeType이 역으로 Notice를 참고하기도 하고 CustomAWSS3Properties를 참고(그것도 그 중 DefaultImage를)하는 것도 조금 어색한 것 같습니다.
차라리 DefaultNoticeGenerateFactory의 getNoticeBaseInfo 메소드에서 swtich나 if로 분기를 태우는건 어떤가요? 코드가 길어지고 분기를 태워서 보기에는 조금 더러워보일 수 있지만 책임 분리면에서는 괜찮지 않을까 하는데 어떻게 생각하시나요?

예를 들어
```
private NoticeBaseInfo getNoticeBaseInfo(final Notice notice) {
		switch (notice.getType()) {
			case FOLLOW -> {
				return new NoticeBaseInfo(
						notice.getFromUser().getUserInfo().getImage(),
						getNickName(notice) + "님이 회원님을 팔로우하기 시작했어요");
			}
			case REVIEW_COMMENT -> {
				return new NoticeBaseInfo(
						customAwss3Properties.getDefaultImage().getComment(),
						getNickName(notice) + "님이 댓글을 달았어요!");
			}
                        ...
			default -> {
                               ...
			}
		}
}
```

2023-06-04 23:25 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
> +	private Long userId;
event publish 할 때 모든 이벤트에서 이미 user를 조회했는데

```java 
public class UserFollowServiceImpl implements UserFollowService {
    ...
    @Transactional(rollbackFor = Exception.class)
    public void follow(String oAuthId, FollowRequest request) {
        User fromUser = userRepository.findByOAuthId(oAuthId).orElseThrow(() -> new DaedongException(DaedongStatus.USER_NOT_FOUND));
        User toUser = userRepository.findById(request.getUserId()).orElseThrow(() -> new DaedongException(DaedongStatus.USER_NOT_FOUND));
        if(fromUser.equals(toUser)) throw new DaedongException(DaedongStatus.SELF_FOLLOW_EXCEPTION);
        if(followRepository.findByFromUserAndToUser(fromUser, toUser).isPresent()) throw new DaedongException(DaedongStatus.FOLLOW_DUPLICATE_EXCEPTION);
        Follow follow = Follow.builder().fromUser(fromUser).toUser(toUser).build();
        followRepository.save(follow);
        eventPublisher.publishEvent(FollowEvent.builder().userId(toUser.getId()).fromUserId(fromUser.getId()).build());
    }
...
}
```

```java 
public class NoticeServiceImpl implements NoticeService{

...
    @Async("notice")
    @TransactionalEventListener
    public void addFollowNotice(FollowEvent event) throws FirebaseMessagingException { // 팔로우 알람
        User user = userRepository.findById(event.getUserId()).orElseThrow(() -> new DaedongException(DaedongStatus.USER_NOT_FOUND));
        User fromUser = userRepository.findById(event.getFromUserId()).orElseThrow(() -> new DaedongException(DaedongStatus.USER_NOT_FOUND));
        Notice notice = Notice.builder()
                .user(user).fromUser(fromUser)
                .contentId(fromUser.getId())
                .type(NoticeType.FOLLOW).build();
        noticeRepository.save(notice);
        fcmService.sendMessageTo(user, noticeTitle(notice), notice.getContent(), notice.getContentId(), notice.getType());
    }
...
}
```
event listener에 들어와서 다시 또 select할 필요가 없어 보였습니다.

해서 유저 id 값으로 바로 notice를 저장하기 위해 변경했습니다.

또한 알림 로직 진행시 유저의 알림 수신 여부 데이터가 필요한데

event listener에선 user 조회 로직을 제거했으니
이 데이터를 전달하기 위해 NoticableEvent (Notice + able + Event)에
담아서 이벤트를 발행했습니다.

일단은 이런 생각에 코드를 변경했는데 혹시 제가 생각하지 못한 
문제가 발생할 수 있는 상황이 호오 호오 옥시 있을까요??

2023-06-04 23:27 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/DefaultNoticeGenerateFactory.java
> +	public DefaultNoticeGenerateFactory(final CustomAWSS3Properties customAwss3Properties) {
네 @RequiredArgsConstructor로 컨벤션 맞추겠습니다.

2023-06-04 23:30 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/DefaultNoticeGenerateFactory.java
> +		final Notice notice,
앗 ㅎㅎ 넵 보통 원래 파라미터 3개 이상부터 다음 줄로 depth 주는데
Notice의 데이터를 각각 넘기다가 Notice 하나로 받으면서 변경하지 않은 것 같네요 ㅎㅎ

2023-06-04 23:32 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticableEvent.java
> +public class NoticableEvent {
NoticableEvent (Notice + able + Event)로 생각해서 만든거긴한데 ㅋㅋㅋㅋㅋ 
조금 의미전달이 부족하다면 변경해 보아야겠네요 ㅎㅎ 
좋은 명칭이 있을까요 ?? ㅎㅎ

2023-06-04 23:35 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
> +		public NoticeBaseInfo(final String image, final String title) {
넵!!

2023-06-04 23:36 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
>   */
네 제거했습니다.

2023-06-04 23:37 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
> +		FirebaseMessagingException {
앗 여기도 원래 파라미터가 여러 개여서 인텔리 제이가 알아서 포멧팅 해준 것을
제가 변경하지 않고 커밋 한 것 같습니다.
수정할게요!!

2023-06-04 23:40 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceImpl.java
> +					.noticeType(NoticeType.REVIEW_COMMENT)
와 꼼꼼하게 안 보셨음 절대로 못 찾는 오류인데

감사합니다 수호님!!!

2023-06-05 02:32 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
> +	public static class NoticeBaseInfo {
Notice 생성 로직 전반적으로 수정하면서 제거했습니다!!!

2023-06-05 02:42 UTC, JayPark7821 commented
> > NoticeDto 생성 로직을 NoticeGenerateFactory에 위임
> > 일단은 NoticeType 추가 후 BiFunction만 구현하면 NoticeGenerateFactory를 사용하는 클라이언트 코드의 변경 없이 확장이 가능하도록 수정했는데
> > NoticeType enum이 조금 지저분해진 것 같아서 혹시 다른 좋은 방법이 떠오르시면 말씀 부탁드려요!!!!
> 
> 음 제가 잘 몰라서 그럴 수 있는데 Enum에서 Enum외의 것들(Notice, CustomAWSS3Properties)에 대해 저런식으로 들고가도 되는지 잘 모르겠습니다ㅠ 또 NoticeType이 역으로 Notice를 참고하기도 하고 CustomAWSS3Properties를 참고(그것도 그 중 DefaultImage를)하는 것도 조금 어색한 것 같습니다. 차라리 DefaultNoticeGenerateFactory의 getNoticeBaseInfo 메소드에서 swtich나 if로 분기를 태우는건 어떤가요? 코드가 길어지고 분기를 태워서 보기에는 조금 더러워보일 수 있지만 책임 분리면에서는 괜찮지 않을까 하는데 어떻게 생각하시나요?
> 
> 예를 들어
> 
> ```
> private NoticeBaseInfo getNoticeBaseInfo(final Notice notice) {
> 		switch (notice.getType()) {
> 			case FOLLOW -> {
> 				return new NoticeBaseInfo(
> 						notice.getFromUser().getUserInfo().getImage(),
> 						getNickName(notice) + "님이 회원님을 팔로우하기 시작했어요");
> 			}
> 			case REVIEW_COMMENT -> {
> 				return new NoticeBaseInfo(
> 						customAwss3Properties.getDefaultImage().getComment(),
> 						getNickName(notice) + "님이 댓글을 달았어요!");
> 			}
>                         ...
> 			default -> {
>                                ...
> 			}
> 		}
> }
> ```

의견 감사합니다.

맞아요 저도 Enum이 너무 많은 것을 알고 있어 찜찜해 여쭤본 거였는데 ㅎㅎ 감사합니다!!

다만 로직은 수호님이 제안 주신 switch case 대신
클래스가 많아지긴 하지만 타입별로 분리해서 변경 대응에 수월하고 확장에 열려있도록
이전 OIDC 로직과 비슷하게 처리하였습니다!!!

리뷰 감사합니다!!!!

2023-06-05 05:27 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticableEvent.java
> +public class NoticableEvent {
어음 그냥 심플하게 NoticeEvent는 어떨까요?ㅎㅎㅎ

2023-06-05 06:25 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
> +	private Long userId;
음 그럼 NoticableEvent에 Long userId와 Long fromUserId가 아닌 User user와 User fromUser를 들고 가는건 어떨까요? 그러면 다시 조회할 필요도 없을 것 같습니다

2023-06-05 06:29 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
> +	private Long userId;
제가 @TransactionalEventListener 어노테이션을 잘 몰라서요!
혹시 영속성 컨텍스트도 같이 공유하나요??
아니라고 한다면 User를 넘겨도 영속성 컨텍스트에 해당 User 정보가 없어서
다시 select 쿼리가 발생할 것 같습니다.

아니면 슬렉에서 말씀드린 것처럼 getReferenceById를 활용해서 프록시 User를 사용해도 될 것 같습니다.

2023-06-05 06:30 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticableEvent.java
> +public class NoticableEvent {
넵!!! NoticeEvent로 수정하겠습니다.

2023-06-05 07:03 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
> +	private Long userId;
앗 로컬에서 테스트해봤는데 영속성 컨텍스트 공유하는 것 같습니다! User 넘겼는데 다시 select 쿼리가 발생하지 않았습니다!

2023-06-05 07:35 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
> +	private Long userId;
수정 완료 했습니다!!!

2023-06-05 08:14 UTC, grand7070 approved these changes

2023-06-05 08:23 UTC, merged