Refactor : jwt filter
daedongbread/bread-map-backend-2 pull request #252
Opened 2023-06-07 23:26 UTC by JayPark7821

jwt 검증시 db에 실제 존재하는 유저인지 확인 로직 추가 + redis캐싱

2023-06-07 23:29 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
jwt 인증시 db에 실제 존재하는 유저인지 확인
최초 db조회 -> redis insert
이후 케싱 만료 전까진 redis에서 유저 존재 유무 확인

2023-06-07 23:34 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/security/token/JwtTokenProvider.java
> +			List.of(new SimpleGrantedAuthority(currentUserInfo.getRoleType().getCode())));
기존 subject(oAuthId) 만 제공
`UserPrincipal userPrincipal = UserPrincipal.create(claims.getSubject(), authorities); // TODO`

변경 CurrentUserInfo 제공
```java
public class CurrentUserInfo {

	private final Long id;
	private final String delimiterValue;  // user -> oAuthId , admin -> email
	private final RoleType roleType;
}
```
추후 필요하다고 판단되는 값 추가 가능

2023-06-09 07:46 UTC, grand7070 requested changes

2023-06-09 07:46 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
여기 부분 이렇게 할 수도 있을 것 같습니다!
```
return userCacheRepository.getUser(oAuthId).orElseGet(() -> {
	final User savedUser = userRepository.findByOAuthId(oAuthId)
			.orElseThrow(() -> new DaedongException(DaedongStatus.USER_NOT_FOUND));
	userCacheRepository.setIfAbsent(savedUser);
	return savedUser;
});
```

2023-06-09 07:46 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserCacheRepository.java
> +				Optional.of(objectMapper.readValue(userInString.get(), User.class)) :
User Entity 자체를 cache한다고 보면 되겠죠? 이렇게 가져왔을때 User Entity로 제대로 인식하여 영속성 컨텍스트에 잘 들어가는지 궁금합니다!

2023-06-09 07:51 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
앗 이부분은 
```java
@Override
	public User loadUserByOAuthId(final String oAuthId) {
		final Optional<User> cachedUser = userCacheRepository.getUser(oAuthId);  // <- 먼저 케싱된 데이터 조회
		if (cachedUser.isPresent()) { // <- 케싱된 데이터 있으면 케싱된 데이터로 바로 return
			return cachedUser.get(); 
		} else {
			final User savedUser = userRepository.findByOAuthId(oAuthId) // <- 케싱된 데이터가 없으면 그때 db에서 select 
				.orElseThrow(() -> new DaedongException(DaedongStatus.USER_NOT_FOUND)); // <- 그런데 db에도 없으면 exception
			userCacheRepository.setIfAbsent(savedUser); // <- db에서 가져온 데이터 케싱
			return savedUser;
		}
	}
```
라서 수호님이 제시하신 방법으로 변경하면 저의 의도와 달라져서...ㅠㅠ

2023-06-09 07:59 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	public User loadUserByOAuthId(final String oAuthId) {
저도 고민했었는데 수호님이 그렇게 말씀해주시니 바로 옮기겠습니다!!!!!ㅎㅎ

2023-06-09 08:01 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/infra/EmbeddedRedisConfig.java
> +@Profile({"default", "local" }) // TODO
또잉?? ㅎㅎ 지울게요!!!!

2023-06-09 08:31 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
엇 둘 다 기능은 같지 않나요??

2023-06-09 08:32 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserCacheRepository.java
> +				Optional.of(objectMapper.readValue(userInString.get(), User.class)) :
아하 캐시로 해당 유저가 존재하는지 확인하고 존재하면 그때 DB에서 유저를 가져오는 것이군요
그럼 User Entity 자체를 value로 넣을 필요는 없지 않나요?

2023-06-09 09:08 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	public User loadUserByOAuthId(final String oAuthId) {
바꾸려고 보니 의존관계가 Circuler가 되네요.. JwtTokenProvider <-> AuthServiceImpl
일단은 UserService 쪽에 넣어 놓고 나중에 구조 변경 시 리팩토링 해야 할 것 같습니다.

2023-06-09 09:10 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/infra/EmbeddedRedisConfig.java
> +		redisServer = new RedisServer(customRedisProperties.getPort());
전달해 주신 application-local 파일로 세팅해서 수호님 환경에서 돌아가도록 다시 원래대로 롤백 해놓았습니다!!

2023-06-09 09:11 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
결국 User를 가져오지만
redis에서 가져오면 db에서 가져오는 것보다 속도가 빠르고
db에 나가는 요청 수를 줄여 줄 수 있을 것 같습니다!!

2023-06-09 09:18 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
엄 제가 올린 코드랑 재현님께서 올려주신 코드가 기능적으로 같지 않나요? 그냥 간결하게만 만든거라...

2023-06-09 09:18 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/global/infra/EmbeddedRedisConfig.java
> +		redisServer = new RedisServer(customRedisProperties.getPort());
앗 혹시 어떤게 문제였을까요?

2023-06-09 09:19 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	public User loadUserByOAuthId(final String oAuthId) {
아고 순환참조가 되는군요 넵넵 그럼 이 부분은 추후에 변경해도 괜찮을 것 같습니다!

2023-06-09 09:21 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserCacheRepository.java
> +				Optional.of(objectMapper.readValue(userInString.get(), User.class)) :
네 지금 현재는 없습니다!!!! 
수정했습니다!!!

2023-06-09 09:25 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java
> +	}
아 헐 .... 죄송합니다.
첫 줄 소스 첫 줄 건너뛰고 봤네요......

맞네요 수호님이 적어주신 코드가 훨씬 보기 좋네요!!!!!

2023-06-09 10:42 UTC, grand7070 approved these changes

2023-06-09 11:36 UTC, merged