Refactor : FlagService
daedongbread/bread-map-backend-2 pull request #261
Opened 2023-06-16 15:19 UTC by JayPark7821

FlagService 리팩토링

2023-06-16 15:24 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/Flag.java
> +	}
Flag가 수정/삭제 불가능한 Flag 값 ("가고 싶어요", "가봤어요")을 static으로 들고 있게 하고
수정 삭제 가능 여부 확인 로직을 flag에 위임

2023-06-16 15:29 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagController.java
> +		@AuthenticationPrincipal CurrentUserInfo currentUserInfo,
Controller 들어오기 전 JwtAuthenticationFilter에서 redis를 통해 유저가 실제 가입한 유저인지 확인하고
SecurityContext에 유저 정보 (CurrentUserInfo)를 담아 놓기 때문에 추가 Service에서 user 조회 시 pk 값 활용을 위해
해당 라인 추가

2023-06-16 15:33 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
> +		return flagRepository.findByUserId(userId).stream()
이미 filter에서 실제 db에 저장되어 있는 유저인지 확인하고 
userId를 SecurityContext에 담아 놓았기 때문에
다시 User를 조회해 올 필요 없어 User 대신 userId로 조회

2023-06-16 15:35 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
> +		if (!flag.isEditable())
검증로직 flag에 위임

2023-06-16 15:50 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
>  			throw new DaedongException(DaedongStatus.FLAG_COLOR_EXCEPTION);
실제 어플리케이션에서도 회색으로 선택하면 아무반응이 없는데....
이부분 필요한 로직인지 궁금합니다.

2023-06-17 03:16 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
>  			throw new DaedongException(DaedongStatus.FLAG_COLOR_EXCEPTION);
엇 어플리케이션 색깔 선택에 회색이 있나요??

2023-06-17 10:24 UTC, grand7070 requested changes

2023-06-17 10:24 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
> +	public FlagBakeryDto getBakeryByFlag(Long userId, Long flagId) { // TODO page?
여기 혹시 getBakeriesByFlag로 바꿔주실 수 있으실까요?

2023-06-17 10:24 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
> +	private Integer getFlagCount(final List<FlagBakeryRepository.BakeryCountInFlag> bakeryCountInFlag,
여기 줄바꿈이 조금 이상한 것 같습니다!

2023-06-17 11:25 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagController.java
> +		@AuthenticationPrincipal CurrentUserInfo currentUserInfo,
네 @CurrentUser로 할 수 있는데 현저 애플리케이션 전체에서 해당 어노테이셔을 oAuthId로 사용 중이어서....
일단 @AuthenticationPrincipal로 사용했어요

음 아이디로 바로 가져오지 않은 이유는 보니까 어드민의 경우 oAuthId 대신 email을 사용하도록 하신 것 같아서
어드민과 일반 유저를 구분하기 위해
CurrentUserInfo에 id, delimiterValue(admin : email, user : oAuthId) , RoleType 이렇게 선언해놓고 같이 사용하려고 생각했었습니다.
어떻게 할까요??

2023-06-17 11:26 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
> +	public FlagBakeryDto getBakeryByFlag(Long userId, Long flagId) { // TODO page?
넵!!!

2023-06-17 13:25 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagController.java
> +		@AuthenticationPrincipal CurrentUserInfo currentUserInfo,
음 일단은 어드민은 API 사용에 id가 사용되는 일이 없어서 @CurrentUser를 기존 oAuthId에서 id로 바꿔도 될 것 같습니다. 해당 작업은 따로 작업 파서 해야 할 것 같습니다. 나중에 어드민이 id를 사용할 일이 생기면 그때 따로 어노테이션 만들어서 하면 되지 않을까 싶습니다.

2023-06-18 14:02 UTC, grand7070 approved these changes

2023-06-18 14:20 UTC, merged