Feature/issue 271
daedongbread/bread-map-backend-2 pull request #279
Opened 2023-07-11 03:24 UTC by JayPark7821

# feat: 빵집별 전체 조회수 -> 일별 + 빵집별 조회수 관리 변경 -#271

BakeryView 도메인 변경
조회수 카운팅 비동기 처리 (redis stream)
조회수 동시성 이슈 처리

2023-07-13 04:19 UTC, grand7070 requested changes

2023-07-13 06:52 UTC, skehdxhd96 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java
> +		return fieldMap;
메소드명 오타났어요~

2023-07-13 06:52 UTC, skehdxhd96 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryViewEventStreamRedisImpl.java
> +public class BakeryViewEventStreamRedisImpl implements BakeryViewEventStream {
저도 Redis Stream은 잘 몰라서 공부를 해봐야 리뷰가 가능할 것 같습니다~ 주말에 한번 이야기해 보시져

2023-07-13 06:52 UTC, skehdxhd96 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
increment로 key에 대한 동시성만 없애주면 조회수는 괜찮을 것 같아요!

다만 repoistory.save는 아마 첫 조회수 다음부터는 save가 자동적으로 merge를 칠것같은데요,
redis에 문제가 있어서 다운되거나 키가 만료될 때 increment가 RDB의 viewCount를 1로 덮어쓸 위험이 있지 않을까 싶습니다!(다행히 increment가 null을 return 하지는 않지만요)

그리고 DB입장에서는 결국 update를 치는거기 때문에 lock이 걸릴텐데, 조회수가 몰렸을 때 update lock으로 인해서 connection time out이 날 확률은 없을까요??(이부분은 제가 redisStream을 잘 몰라서, 10초간 모아놓은 조회수를 한번에 update친다면 상관 없는 부분이긴 합니다!)

2023-07-13 06:55 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryView.java
> +	private Long bakeryId;
들어갈 수 있는데
그럴 필요가 없다고 생각해서 일부러 연관관계 끊어내고 아이디 값만 가지고 있게 했어요!!

연관관계 맺어 놓으면 insert 할 때 Bakery select 해와서 넘겨주거나
기억은 잘 안 나지만 jpa에서 save 할 때 내부적으로 연관관계 맺은 테이블 데이터 있는지 확인 (select query) 하는 걸로 알고 있는데
단순 조회 수 카운트하는 곳에서 이런 데이터 정합성 체크하는 게 굳이 필요할까??라는 생각이 가장 크구용

연관관계 이렇게 끊어 놓으면 나중에 NoSql 도입할 때
이 테이블은 그 어디에도 의존하고 있지 않아서 편할 거라 생각했습니다.

2023-07-13 06:55 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryViewEventStreamRedisImpl.java
> +public class BakeryViewEventStreamRedisImpl implements BakeryViewEventStream {
Redis Stream을 사용하신 이유가 궁금합니다!
-> 의식의 흐름이 
1. getBakery는 사용자의 빵집 상세정보 요청을 처리하는 메서드인데 여기서 조회 수 카운트까지 책임지는 것을 끊어 내고 싶은 마음
( 조회 수 카운트의 변경이 일어났을 때 getBakery도 수정을 해야 하는 상황 방지)

2. 그럼 Facade나 aggregator 클래스를 만들어서 처리해야 하나??  

3. 근데 큰 차이는 없겠지만 조회 수 카운트 +1 하는 시간만큼 사용자가 더 기다려야 할 필요는 없지 않나??

4. 그럼  조회 수 카운트는 비동기 적으로 처리하자라는 결론

5. 이걸 해결하기 위해서 어떤 기술을 사용할까 생각하다. 

6. 이미 프로젝트에서 redis를 사용하고 있고 최근에 redis streams 관련해서 찾아봤고 또 해당 기술이 가지고 있는 여러 장점들을 생각해 봤을 때 사용해 보는 것도 좋겠다는 결론에 도달했네요


코드로는 빵집 조회 event publish/listen 목적으로 사용되는 것 같은데 맞나요?
-> 네 맞습니다. 
빵집 조회 event 발행
listen 하는 쪽에선 해당 event가 발행될 때마다 조회 수 +1 처리

2023-07-13 06:57 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
앞에선 increment로 redis 자체에서는 동시성 문제가 없어도 여기서 동시성 문제가 발생할 여지가 혹시 있을까요?
-> 앗! 지금 다시 보니 그렇네요 save에서 레이스 컨디션이 발생할 수 있겠네요……

근데 최종적인 count 데이터는 redis에 보관되어 있고,
조회 수 자체가 그렇게 중요한 데이터가 아니라서 크게 문제 될 건 없을 것 같은데

혹시 좋은 아이디어 있으시면 말씀해 주세요!!!!!!!

또 같은 key(bakeryId, viewDate)로 save 해도 문제가 없나요?
-> 해당 키로 데이터 있으면 update 되고 없다면 insert 될 텐데 수호님이 생각하시는 문제가 어떤 문제인지 모르겠어요!!


repository에서 가져와서 save 하면 dirty checking이 될 것 같은데 그냥 save할 땐 문제가 없는지 헷갈리네요…
-> 굳이 select query 한 번 더 날려서 가져온 다음 save할 필요가 없다고 생각합니다. 어차피 최종적으로 저장할 데이터( 조회 수 )는
redis에 들고 있고 몇 번이 들어오든 최종적으로 redis에 들고 있는 데이터로 저장만 하면 되지 않을까요??

2023-07-13 07:08 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java
> +		return fieldMap;
앗 ㅋㅋㅋㅋ 감사합니다. 수정할게요!!!

2023-07-13 07:18 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
다만 repoistory.save는 아마 첫 조회수 다음부터는 save가 자동적으로 merge를 칠것같은데요,
redis에 문제가 있어서 다운되거나 키가 만료될 때 increment가 RDB의 viewCount를 1로 덮어쓸 위험이 있지 않을까 싶습니다!(다행히 increment가 null을 return 하지는 않지만요)
-> 앗 이부분 생각 못하고있었네요
음.... increment 값이 1이면 db select 날려보고 이미 값이 1 이상으로 존재하면 그 값 + 1 해서 다시 redis에 넣는 정도로 풀어 볼 수 있을 것 같네요
다른 좋은 의견 부탁드려요!!!!!!!!

그리고 DB입장에서는 결국 update를 치는거기 때문에 lock이 걸릴텐데, 조회수가 몰렸을 때 update lock으로 인해서 connection time out이 날 확률은 없을까요??(이부분은 제가 redisStream을 잘 몰라서, 10초간 모아놓은 조회수를 한번에 update친다면 상관 없는 부분이긴 합니다!) 
-> 이부분도 흐음 잠깐 생각해봤는데 1차 적으로 increment 값이 x배수 일때 db에 저장 하거나 시간 기준으로 일정 시간 모아서 저장 정도로 풀어보면 어떨까 생각합니다. 뭐가 좋을까요?? 

근데 connection time out 으흐흐 좋네요 그때쯤이면 인프라적으로 다른 기술들 활용하야 하지 않을까 싶네용 ㅋㅋ

2023-07-13 08:20 UTC, skehdxhd96 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
Redis Stream보다 조회수를 Redis에 쌓아놓는 형식으로만 구현하고,
Spring Scheduler로 일정 주기마다 업데이트 치는게 어떨까 하는데,

다른분들 생각은 어떠신가요?? 아무래도 조회수가 여러군데 있다 보니 방식은 통일해야 할 것 같아요

지금 제가 진행중인 큐레이션에도 조회수가 있어서, 정해진 방식을 따르려고 합니다~!!

2023-07-13 12:30 UTC, k-gn reviewed
고생하셨습니다 재현님! 

저는 Redis Stream 에 대한 공부와 이해가 저는 좀 더 필요할 것 같네요 ㅠㅠ

2023-07-13 12:30 UTC, k-gn commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
저는 지금 방식도 너무 좋아보이는데 ㅠㅠ

그리구 주 데이터인 increment 값 자체엔 동시성 문제가 없어보이는데
save 에 대한 동시성 고민이 크게 의미가 있나 싶기도 합니다..!

---

redis 가 다운될 때의 복구/대응 방안은 다음에 따로 이슈를 만들고 고민해보면 좋을 것 같습니다!

> 음.... increment 값이 1이면 db select 날려보고 이미 값이 1 이상으로 존재하면 그 값 + 1 해서 다시 redis에 넣는 정도로 풀어 볼 수 있을 것 같네요

값이 1이냐 아니냐 외에 키가 단순히 만료되었는지 여부만 파악하여 처리할 순 없을까요??


> 이부분도 흐음 잠깐 생각해봤는데 1차 적으로 increment 값이 x배수 일때 db에 저장 하거나 시간 기준으로 일정 시간 모아서 저장 정도로 풀어보면 어떨까 생각합니다. 뭐가 좋을까요??

배치에서 chunk 지향 처리를 하는 것 처럼 어느정도 모아서 저장하는 방식이 좋을 것 같습니다!

2023-07-13 13:27 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
> Redis Stream보다 조회수를 Redis에 쌓아놓는 형식으로만 구현하고,
Spring Scheduler로 일정 주기마다 업데이트 치는게 어떨까 하는데, 

-> Scheduler로 일정 일정 주기마다 전체 빵집 조회 수를 한 번에 업데이트하신다는 말씀이신가요???
만약 그렇다고 한다면 지금 인스턴스 오토 스케일 그룹에 들어가있는데 스케일 아웃 되어서 멀티 인스턴스 상황일 때
그 1개 이상의 인스턴스에서 동시에 빵집 count 만큼 한 번에 db에 쓰려고 달려들면....
그러면 또 한 개 인스턴스에서 스케줄러 돌면 다른 곳은 못 돌게 처리해야 하고.......ㅎㅎ 
어떻게 생각하시나요???

2023-07-13 13:39 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
@k-gn 
> 저는 지금 방식도 너무 좋아보이는데 ㅠㅠ

-> 감사합니다. ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

> 값이 1이냐 아니냐 외에 키가 단순히 만료되었는지 여부만 파악하여 처리할 순 없을까요??
-> 조회 수를 일별로 카운트하기 때문에 ttl 타임을 하루보다 조금 더 길게 세팅하려고 합니다.
키가 일단 만료되면 그 여부는 파악할 수가 없을 것 같아요!!
이부분은 수정해서 다시 올려볼게요!!!!

> 배치에서 chunk 지향 처리를 하는 것 처럼 어느정도 모아서 저장하는 방식이 좋을 것 같습니다!
->  이부분은 고민이 좀 필요할 것 같아요 일단 저는 조회수 카운트를 특정 숫자의 배수이면 업데이트 정도로 생각했어요

2023-07-14 04:29 UTC, k-gn approved these changes

2023-07-14 04:33 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryView.java
> +	private Long bakeryId;
아하 그렇군요 감사합니다!

2023-07-14 04:35 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryViewEventStreamRedisImpl.java
> +public class BakeryViewEventStreamRedisImpl implements BakeryViewEventStream {
단순 event publis/listen이면 Spring EventListener로 해도 되지 않나요?

2023-07-14 04:51 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryViewEventStreamRedisImpl.java
> +public class BakeryViewEventStreamRedisImpl implements BakeryViewEventStream {
네 맞아여 그렇게도 처리 가능한데 제가 생각에는 단점이 명확해서요

| spring EventListener | Redis stream|
|-------------------|----------------|
|이벤트를 발행한 인스턴스에서`만` 처리가 가능하다  |  발행된 이밴트 리스너 그룹의 어느 인스턴스인지 상관없이 처리 가능|
| 이벤트는 발행했는데 그 이벤트를 처리하기전에 인스턴스가 다운되면 해당 이벤트는 유실 | 발행된 이벤트는 Redis stream에 쌓여있어서 인스턴스가 다운되더라도 stream에 데이터만 남아있다면 인스턴스가 올라오는시점에 해당 이벤트 처리가능|
| 발행된 이벤트가 언제 처리될지 모름.....  <br /> 첫 번째 말씀드린 것과 일맥상통한데 이벤트를 발행한 인스턴스에서만 처리 가능하다 보니 해당 인스턴스 상황에 따라서 처리하는데 진짜 오래걸릴때도 있더라구요 | 발행된 이벤트를 읽어오는 주기 설정 가능 |

제가 생각하는 이유는 이정도?? 인데 
혹시 제가 모르는 Spring EventListener로 처리했을때 장점이나 redis stream를 사용했을때 단점 이 있는지 궁금합니다!!!!

2023-07-14 06:47 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryViewEventStreamRedisImpl.java
> +public class BakeryViewEventStreamRedisImpl implements BakeryViewEventStream {
아 spring eventlistener를 말씀드린건 성능보다는 이벤트 listen으로 동작을 하는 것도 결국은 하나의 API 호출에 대한 동작이어서 연속성을 가져야 한다는 점에서 외부 컴포넌트(redis)를 타는게 맞나 생각이 들었습니다. MSA 구조나 로그 같이 어플리케이션 로직이 아닐때는 MQ를 태우는게 맞을 것 같은데 같은 어플리케이션 로직, 특히 조회수 증가라는 기능에 대해 mq를 쓰는 것도 생소했던 것 같습니다
그런데 말씀 주신것처럼 인스턴스(저희는 컨테이너 or EC2) 다운 문제, 같은 인스턴스에서 이벤트 처리도 있고 redis stream 사용에 대해 큰 문제가 없을 것 같아 redis stream 사용도 좋을 것 같습니다
두개 차이에 대해 잘 몰랐던 것도 있었는데 자세히 말씀해주셔서 감사합니다!ㅎㅎ
다만 아직 괜찮을지 싶은건 어쨌든 외부 컴포넌트를 타므로 네트워크 I/O 발생과 모든 빵집의 조회수(조회가 안되면 없겠지만)가 redis에 있을텐데 이때 redis 가용 메모리 양, redis 관리 포인트 증가이긴 합니당...

2023-07-14 06:58 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
엄 지금 헷갈리는게 같은 트랜잭션에선
```
repository.save(Entity.builder().id(1L).build())
repository.save(Entity.builder().id(1L).build())
```
이렇게, 다른 트랜잭션에선 ```repository.save(Entity.builder().id(1L).build())``` 이렇게 했을때 단순 update로 치는지가 헷갈립니다

말씀주신 것처럼 보통은 동시성 문제가 크게 영향은 안 주겠으나 db write때 race condition 문제도 있을 수 있을 것 같고, redis 다운시 문제도 생각은 해봐야겠네요
일단 제가 기억하기론 조회수가 유저한테는 보이지 않는다고 알고 있는데 혹시 맞을까요? 그러면 실시간성 유지가 필요하지 않을테니 스케쥴링으로 주기적으로 DB에 bulk 업데이트가 좋지 않을까 싶습니다.
스케쥴링 관련해서는 Quartz로 하면 멀티 인스턴스여도 단일 인스턴스에서만 스케쥴링 된다고 본 것 같습니다

2023-07-14 07:38 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
> 엄 지금 헷갈리는게 같은 트랜잭션에선
repository.save(Entity.builder().id(1L).build())
repository.save(Entity.builder().id(1L).build())
이렇게, 다른 트랜잭션에선 repository.save(Entity.builder().id(1L).build()) 이렇게 했을때 단순 update로 치는지가 헷갈립니다

-> 이부분은 위 답변 https://github.com/daedongbread/bread-map-backend-2/pull/279#discussion_r1262100473  해당 키로 데이터 있으면 update 되고 없다면 insert 될 텐데 수호님이 생각하시는 문제가 어떤 문제인지 모르겠어요!! 이거 여쭤보신거가 맞나용??

JpaRepository 구현체 따라 내려가면 
![image](https://github.com/daedongbread/bread-map-backend-2/assets/60100532/6ed1c3ce-5ac5-489f-95f8-ab7db964af82)

SimpleJpaRepository에 save메소드가 있는데 

![image](https://github.com/daedongbread/bread-map-backend-2/assets/60100532/8cfde0cd-fdfe-486c-b269-bdf1e2c8f048)

isNew가 아니면 머지 하죠

isNew를 또 찾아보면
![image](https://github.com/daedongbread/bread-map-backend-2/assets/60100532/39ee8904-2f90-48ab-983d-2e355252b434)

간단히 말해 id값이 있으면 merge 없으면 persist입니다.

```java
@Transactional
@SpringBootTest
class MergeTest {

	@Autowired
	private BakeryViewRepository repository;

	@Autowired
	EntityManager em;

	private final Long bakeryId = 777L;
	private final LocalDate date = LocalDate.now();

	@BeforeEach
	void setUp() {
		repository.save(new BakeryView(bakeryId, date, 1L));
		clearContext();
	}

	@Test
	void mergeTest() throws Exception{
		final Long updatedViewCount = 3L;
		repository.save(new BakeryView(bakeryId, date, updatedViewCount));
		clearContext();

		final BakeryView bakeryView = repository.findById(new BakeryViewId(bakeryId, date)).orElseThrow();
		assertThat(bakeryView.getViewCount()).isEqualTo(updatedViewCount);
	}

	private void clearContext() {
		em.flush();
		em.clear();
	}
}
```
헷갈리시면 직접 테스트 코드를 짜보시면 됩니다!!!!!!!!!!!! ㅋㅋㅋㅋㅋㅋㅋ



> 스케쥴링으로 주기적으로 DB에 bulk 업데이트가 좋지 않을까 싶습니다.
 스케쥴링 관련해서는 Quartz로 하면 멀티 인스턴스여도 단일 인스턴스에서만 스케쥴링 된다고 본 것 같습니다

-> 스케쥴 돌려서 처리하는것도 데이터를 모아 놓아야하는데 그러면 redis가 다운되었을때 문제는 스케쥴러로 처리하는게 더 리스크가 크다고 보는데 어떻게 생각하시나요?? 조회수 폭증한 빵집이 있다고 가정하고 극단적으로 뭐 한 2천 조회수가 쌓여있는데 스케쥴러가 돌기전에 redis가 다운되어 버린다면.... 흐음 일단은 지금 상태로 가는게 어떻까 생각하는데 어떤가요??

2023-07-14 14:16 UTC, skehdxhd96 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
Redis Stream으로 가도 괜찮을것 같습니다

다만 현재 레디스 인스턴스 확인해보니 t2 micro 인데, 세션 + 캐싱 + mq 등등 다 하나로 처리해야 하니 조금 불안하긴 하네요. prod라도 모니터링을 걸어놓는건 어떨까요..??

2023-07-14 14:18 UTC, skehdxhd96 approved these changes
EventListener와 RedisStream비교해주신거 너무 좋았어요~

2023-07-14 14:19 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
앗 isNew로 select를 날려줬군요...ㅎㅎㅎ 기본 상식 부족인걸로....ㅎㅎ 감사합니다!

음 redis 다운 문제는 cluster 구성으로 인프라적으로 해결을 해야 할 것 같습니다
아니면 save때 분산락 사용하는 방법도 있을 것 같습니다!
그런데 음 아직 트래픽도 저조하기도 할테니 일단은 지금 상태로 넘기는 것도 될 것 같긴 합니다. 만약 일단 이렇게 넘어가실 예정이시라면 옆에 TODO 표시해주실 수 있으실까요?

2023-07-14 14:31 UTC, grand7070 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
> Redis Stream으로 가도 괜찮을것 같습니다
> 
> 다만 현재 레디스 인스턴스 확인해보니 t2 micro 인데, 세션 + 캐싱 + mq 등등 다 하나로 처리해야 하니 조금 불안하긴 하네요. prod라도 모니터링을 걸어놓는건 어떨까요..??

넵 redis 의존성이 점점 커져서 대응 필요성이 있긴 할 것 같습니다. 모니터링은 어떤 방식 말씀이실까요? 근데 저희 redis를 세션으로도 쓰나요??

2023-07-15 14:20 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/view/BakeryViewEventStreamListener.java
> +		repository.save(BakeryView.builder()
> 음 redis 다운 문제는 cluster 구성으로 인프라적으로 해결을 해야 할 것 같습니다
아니면 save때 분산락 사용하는 방법도 있을 것 같습니다!

-> 해당 부분 이슈로 등록해놓을게요~~

2023-07-15 14:20 UTC, merged