feat: OpenSearch 검색엔진 도입 초기 설정 및 API 구현
daedongbread/bread-map-backend-2 pull request #346
Opened 2023-10-02 19:45 UTC by chris910512

### 변경사항
- OpenSearch Bean 추가
- 검색엔진 데이터 적재 배치 추가
- 키워드 검색 v2 추가

# tag: feature: OpenSearch 검색엔진 도입 초기 설정 및 API 구현 -#345

2023-10-18 07:18 UTC, JayPark7821 requested changes
브랜치는 dev 브랜치를 기준으로 생성 부탁드립니다

2023-10-30 13:45 UTC, JayPark7821 requested changes

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/utils/UnicodeHandler.java
> +@Component
클래스의 모든 맴버 변수, 메소드가 전부 스테틱인데
주입받아서 사용할 필요가 있을까 라는 생각이 드네요

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/global/infra/EmbeddedRedisConfig.java
> +//		, "local"
특별한 이유가 없다면 원복 부탁드립니다

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/dto/keyword/CommonLoadData.java
> +    private Long reviewCount;
변경주기가 매우 짧은 데이터일텐데 
데이터 싱크는 어떻게 맞추실 계획이신가용?!

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/dto/ReviewComparator.java
> +public class ReviewComparator implements Comparator<SearchEngineDto> {
functionalInterface로 대체하는게 좋아보이는데 어떻게 생각하시나요??

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/dto/DistanceComparator.java
> +public class DistanceComparator implements Comparator<SearchEngineDto> {
functionalInterface로 대체하는게 좋아보이는데 어떻게 생각하시나요??

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/SearchV2Controller.java
> +
searchService에서 가져올때 sort된 List<String>으로 가져오는게 좋아 보여요!

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/SearchV2Controller.java
> +public class SearchV2Controller {
controller( 외부와의 인터페이스)에서 로직을 처리하기 보단 
서비스에서 필요한 처리를 완료하고 완성된 데이터를 가져오는게 좋아 보입니다.

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/admin/openSearch/dto/validation/LowerCaseValidator.java
> +    public boolean isValid(String value, ConstraintValidatorContext context) {
소문자를 벨리데이트 꼭 해야하는 이유가 있을까요??
그냥 서버에서 toLowerCase()호출하면 발생할 수 있는 다른 문제가 있을까요?

2023-10-30 13:45 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryQueryRepository.java
> +				.where((product.productType.eq(ProductType.BREAD)).and(bakery.createdAt.goe(LocalDateTime.now().minusHours(1))))
만약 신규 데이터가 아니라면 
loadEntireData()가 호출되기 전까지는 이전 데이터가 남아 있는 상황인건가요?

2023-11-01 00:24 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/dto/keyword/CommonLoadData.java
> +    private Long reviewCount;
es에 저장할 필요가 있나라는 생각이 들어요!!!
flow가 유저 검색 단어 입력 -> 검색어 추천(자동완성) -> 사용자 선택 -> id로 db조회 후 리턴 식으로 흐르는거 아닌가용?!

2023-11-01 00:27 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryQueryRepository.java
> +				.where((product.productType.eq(ProductType.BREAD)).and(bakery.createdAt.goe(LocalDateTime.now().minusHours(1))))
[요기](https://github.com/daedongbread/bread-map-backend-2/pull/346#discussion_r1376218791)서 말씀드린 부분과 비슷한 맥락에서 말씀드린거에용

빵집 데이터 update시 applicationEvent 등으로 해당부분 업데이트 해주거나 하는건 어떻게 생각하시나용?!!

2023-11-03 13:38 UTC, JayPark7821 requested changes
생성하신 endPoint들 restDocs 만들어주세용!!!

2023-11-03 13:38 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/OpenSearchLoadScheduler.java
> +                System.out.println("Job loadEntireData executed by this instance");
log로 변경 부탁드려요

2023-11-03 13:38 UTC, JayPark7821 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/SearchV2Controller.java
> +    }
흐음....불필요한 코드가
그냥

```java
SearchResultResponse searchResultResponse = searchService.searchEngine(oAuthId, keyword, latitude, longitude, searchType);

return new ApiResponse<>(searchResultResponse);
```
이러면 끝아닌가요?.... 읽기만 더 힘든거같아요!!!!

2023-11-15 00:42 UTC, chris910512 commented on src/main/java/com/depromeet/breadmapbackend/domain/search/events/OpenSearchDeleteEvent.java
> +public class OpenSearchDeleteEvent extends ApplicationEvent {
빵집 -> 미게시 처리
빵 -> 전체 삭제 후 재 적재 (건별 삭제기능 없음)
2개 로직 추가했습니다

2023-11-21 00:59 UTC, merged